name: "Build docker image on local runner"
description: "Build and publish docker image to Zowe docker registry"
inputs:
  release:
    description: "Set to true if this is a formal release"
    required: false
    default: ""
  registry:
    description: "Docker registry"
    required: true
    default: ""
  base-directory:
    description: "Base directory where image Dockerfiles are located"
    required: true
    default: ""
  linux-distro:
    description: "Linux distro name. This should be the second level folder name."
    required: false
    default: "ubuntu"
  cpu-arch:
    description: "CPU architecture name. This should be the third level folde rname."
    required: false
    default: "amd64"
runs:
  using: "composite"
  steps:
    - name: Set image name, version, metadata and registry
      run: |
        IMAGE_VERSION=$(cat ${{ inputs.base-directory }}/${{ inputs.linux-distro }}/${{ inputs.cpu-arch }}/Dockerfile |  awk "/LABEL /{x=NR+100}(NR<=x){print}" | grep version= | head -n 1 |  awk -F= '{print $2;}' | sed -e 's/\\//g' | sed -e 's/"//g' | xargs)
        [ -z "${IMAGE_VERSION}" ] && echo "Cannot determine version of the image" && exit 1
        IMAGE_NAME=$(basename ${{ inputs.base-directory }})
        echo "IMAGE_VERSION=${IMAGE_VERSION}" >> $GITHUB_ENV
        echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
        IMAGE_METADATA=
        [ -n "${{ github.event.pull_request.number }}" ] && IMAGE_METADATA=pr-${{ github.event.pull_request.number }}
        [ -z "${IMAGE_METADATA}" ] && IMAGE_METADATA=${GITHUB_REF#refs/heads/}
        [ "${IMAGE_METADATA}" = "master" ] && IMAGE_METADATA=snapshot
        IMAGE_METADATA=$(echo "${IMAGE_METADATA}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-zA-Z0-9]/\-/g')
        [ "${{ inputs.release }}" = "true" ] && IMAGE_METADATA=
        [ -n "${IMAGE_METADATA}" ] && echo "IMAGE_METADATA=.${IMAGE_METADATA}-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
        IMAGE_TAG=${IMAGE_VERSION}-${{ inputs.linux-distro }}-${{ inputs.cpu-arch }}${IMAGE_METADATA}
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
        exit 0
      shell: bash

    - name: build image
      working-directory: ${{ inputs.base-directory }}/${{ inputs.linux-distro }}/${{ inputs.cpu-arch }}
      run: |
        docker build --no-cache=true -t ${{ inputs.registry }}/ompzowe/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
      shell: bash

    - name: publish image
      working-directory: ${{ inputs.base-directory }}/${{ inputs.linux-distro }}/${{ inputs.cpu-arch }}
      run: |
        docker push ${{ inputs.registry }}/ompzowe/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      shell: bash
