name: "Create docker manifest"
description: "This action helps to create and publish docker manifest."
inputs:
  linux-distro:
    description: "Linux distro name. This should be the second level folder name."
    required: false
    default: "ubuntu"
  cpu-arch-list:
    description: "CPU architecture name list seperated by space."
    required: false
    default: "amd64 s390x"

runs:
  using: "composite"
  steps:
    - name: define manifest
      run: |
        export DOCKER_CLI_EXPERIMENTAL=enabled
        amends=
        for arch in "${{ inputs.cpu-arch-list }}" ; do
          amend=$(echo "${IMAGE_MANIFEST_AMEND}" | sed -e "s/_ARCH_/${arch}/")
          echo "Adding ${amend}"
          amends="${amends} --amend ${amend}"
        done
        echo "Creating ${{ env.IMAGE_MANIFEST }}"
        docker manifest create ${{ env.IMAGE_MANIFEST }} ${amends}
        docker manifest push ${{ env.IMAGE_MANIFEST }}
      shell: bash
