name: Generate Source Image

# Note: github actions are not very powerful or good. There doesn't seem to be a good way to
#       enforce that you run other actions before this one. So, please do run these first,
#       in this order, so that something doesn't blow up:
#       zowe-actions/shared-actions/docker-prepare@main
####       actions/tern-action@v1
#       actions/setup-node@v2
#       then run:
#       zowe-actions/shared-actions/docker-build-local@main
#       with args:
#        dockerfile: ${{ github.action_path }}/../utils/Dockerfile.sources
#        build-arg-list: IMAGE_NAME=${{ github.event.inputs.image-name }} NODE_VERSION=${{ github.event.inputs.node-version }}  

inputs:
#Ex https://zowe.jfrog.io/artifactory/docker-snapshot/ompzowe/base/0.0.1-ubi-amd64.users-jack-base-images-67
  image-name:
    description: 'The name of a container image in a registry in the form of [my.registry.address:port/]repositoryname/tag'
    required: true
  node-version:
    description: 'Version of nodejs to download source for. If not specified, no source is downloaded'
    required: false
    default: ""
  registry-user:
    description: 'Username to login to the docker registry where the input image exists'
    required: false
  registry-password:
    description: 'Password to login to the docker registry where the input image exists'
    required: false
#  redhat-registry:
#    description: 'Username to login to the redhat container registry where the input image exists'
#    required: false
#  redhat-password:
#    description: 'Password to login to the redhat container registry where the input image exists'

runs:
  using: composite
  steps:
#    - name: Setup docker env
#      uses: zowe-actions/shared-actions/docker-prepare@main
#      with:
#        registry-user: ${{ github.event.inputs.registry-user }}
#        registry-password: ${{ github.event.inputs.registry-password }}
#        base-directory: ${{ github.action_path }}/../utils
#        redhat-registry-user: ${{ github.event.inputs.redhat-registry-user }}
#        redhat-registry-password: ${{ github.event.inputs.redhat-registry-password }}

    - name: Login to registry
      run: |
        echo "${{ inputs.registry-password }}" | docker login --username "${{ inputs.registry-user }}" --password-stdin ${{ env.ZOWE_DOCKER_REGISTRY }}
      shell: bash

    - name: Login to Redhat registry
      run: |
        [ -n "${{ inputs.redhat-registry }}" ] && echo "${{ inputs.redhat-registry-password }}" | docker login --username "${{ inputs.redhat-registry-user }}" --password-stdin ${{ inputs.redhat-registry }}
        exit 0
      shell: bash

    - name: Set tag by env
      run: |
        echo "IMAGE_NAME_FULL_REMOTE=${{ inputs.image-name }}-source" >> $GITHUB_ENV
      shell: bash

    - name: Make Bill of Materials with Tern
#      run: |
#        python3 -m venv ternenv
#        cd ternenv
#        source bin/activate
#        pip install tern
#        tern report -o ${{ github.workspace }}/tern.json -i ${{ inputs.image-name }}
      run: |
        git clone https://github.com/tern-tools/tern.git
        cd tern
        docker build -f docker/Dockerfile -t ternd .
        ./docker_run.sh ternd "report -f json -i ${{ inputs.image-name }}" > ${{ github.workspace }}/tern.json
      shell: bash
            
#    - name: Make Bill of Materials
#      uses: actions/tern-action@v1
#      id: scan
#      with:
#        image: ${{ github.event.inputs.image-name }}
#        format: json
#        output: ${{ github.action_path }}/tern.json

#    - name: Prepare nodejs
#      uses: actions/setup-node@v2
#      with:
#        node-version: '12'
          
    - name: Transform Bill
      run: |
        cd "${{ github.action_path }}/../utils"
        node "generate-attributions.js" "${{ github.workspace }}/tern.json"
      shell: bash

#    - uses: actions/upload-artifact@v2
#      with:
#        name: NOTICE.txt
#        path: ${{ github.action_path }}/../utils/NOTICE.txt

    - name: Copy EPL license for container
      run: |
        cp "${{ github.action_path }}/../LICENSE" "${{ github.action_path }}/../utils/LICENSE.txt"
        cp -r "${{ github.action_path }}/../utils" "${{ github.workspace }}/docker-build-local"
      shell: bash
        
    - name: Get node source
      run: |
        if [ -n "${{ inputs.node-version }}" ]; then wget "https://nodejs.org/dist/v${{ inputs.node-version }}/node-v${{ inputs.node-version }}.tar.xz" -o "${{ github.workspace }}/docker-build-local/node-v${{ inputs.node-version }}.tar.xz"; fi
        ls -ltr "${{ github.workspace }}/docker-build-local"
      shell: bash

#    - uses: zowe-actions/shared-actions/docker-build-local@main
#      with:
#        dockerfile: ${{ github.action_path }}/../utils/Dockerfile.sources
#        build-arg-list: IMAGE_NAME=${{ github.event.inputs.image-name }} NODE_VERSION=${{ github.event.inputs.node-version }}
