name: "Publish"
description: "Publish to artifactory for all project builds"
inputs:
  artifacts:
    description: 'artifacts to upload, also support multiple line inputs'
    required: true
  perform-release:
    description: 'flag to perform steps to release'
    required: true
  pre-release-string:
    description: 'pre-release string'
    required: false
  publish-target-path:
    description: path format for publishing to artifactory
    required: false
    default: '{repository}/{package}{subproject}/{version}{branchtag-uc}/'

runs:
  using: 'node12'
  main: 'dist/index.js'
