name: "Check permission"
description: "Permission check for current github actor to see if it has write access"
inputs:
  user: 
    description: 'user to be checked'
    required: true
  github-repo:
    description: 'github repository'
    required: true
  github-user: 
    description: 'github user for authenticating api requests'
    required: true
  github-passwd:
    description: 'github passwd for authenticating api requests'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        cd ${{github.action_path}}/..
        pwd
        ls -al
        cd generic-setup
        cat process-manifest.js
        npm install
        cd ${{github.action_path}}
        node index.js
      shell: bash
      env:
        INPUT_USER: ${{ inputs.user }}
        INPUT_GITHUB-REPO: ${{ inputs.github-repo }}
        INPUT_GITHUB-USER: ${{ inputs.github-user }}
        INPUT_GITHUB-PASSWD: ${{ inputs.github-passwd }}